# Generated by Django 4.1.3 on 2022-11-19 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("tmdb", models.IntegerField(blank=True, null=True)),
                ("tvdb", models.IntegerField(blank=True, null=True)),
                (
                    "imdb_id",
                    models.IntegerField(blank=True, primary_key=True, serialize=False),
                ),
                ("imdb_episode_id", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                ("otitle", models.CharField(blank=True, max_length=50, null=True)),
                ("original", models.BooleanField(blank=True, null=True)),
                ("serie", models.BooleanField(blank=True, null=True)),
                ("episode", models.IntegerField(blank=True, null=True)),
                (
                    "episodetitle",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                ("banners", models.URLField(blank=True, max_length=150, null=True)),
                ("posters", models.URLField(blank=True, max_length=150, null=True)),
                ("runtime", models.IntegerField(blank=True, null=True)),
                ("fsk", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "pid",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "otitle",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("internal_id", models.IntegerField(blank=True)),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                ("subtitles", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "movie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="movies.movie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="movies.series",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=4, null=True)),
                ("url", models.URLField(blank=True, max_length=150, null=True)),
                ("seasonurl", models.URLField(blank=True, max_length=150, null=True)),
                ("available", models.BooleanField(blank=True, null=True)),
                ("resolution", models.CharField(blank=True, max_length=20, null=True)),
                ("audio", models.CharField(blank=True, max_length=20, null=True)),
                ("added", models.DateTimeField(blank=True, null=True)),
                ("modified", models.DateTimeField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("expires", models.DateTimeField(blank=True, null=True)),
                (
                    "movie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="movies.version",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movies_provided",
                        to="movies.provider",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="movie_roles", to="movies.person"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="companies",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="movies_produced",
                to="movies.company",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="countries",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="movies", to="movies.country"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="directors",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="movies_produced",
                to="movies.person",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="movies", to="movies.genre"
            ),
        ),
    ]
