# Generated by Django 4.1.3 on 2022-11-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Countries",
            new_name="Country",
        ),
        migrations.AddField(
            model_name="movie",
            name="countries",
            field=models.ManyToManyField(related_name="movies", to="movies.country"),
        ),
    ]
