# Generated by Django 4.1.3 on 2022-11-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_rename_countries_country_movie_countries"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="type",
            field=models.CharField(default="ABO", max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                blank=True, related_name="movie_roles", to="movies.person"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="banner",
            field=models.URLField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="movie",
            name="companies",
            field=models.ManyToManyField(
                blank=True, related_name="movies_produced", to="movies.company"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="countries",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="movies.country"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="directors",
            field=models.ManyToManyField(
                blank=True, related_name="movies_produced", to="movies.person"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="episodetitle",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="movies.genre"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="otitle",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.URLField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
